String categorizeComplaint(String complaintText) {
  final Map<String, String> categoryRules = {

    // MINAGRI

    "agriculture": "MINAGRI",
    "farming": "MINAGRI",
    "farmers": "MINAGRI",
    "livestock": "MINAGRI",
    "irrigation": "MINAGRI",
    "fertilizers": "MINAGRI",
    "seeds": "MINAGRI",
    "crop": "MINAGRI",
    "harvest": "MINAGRI",
    "plantation": "MINAGRI",
    "agronomy": "MINAGRI",
    "veterinary": "MINAGRI",
    "dairy": "MINAGRI",
    "pesticides": "MINAGRI",
    "organic farming": "MINAGRI",
    "greenhouses": "MINAGRI",
    "agribusiness": "MINAGRI",
    "post-harvest": "MINAGRI",
    "food security": "MINAGRI",
    "agrifood": "MINAGRI",
    "land use": "MINAGRI",
    "soil fertility": "MINAGRI",
    "drought": "MINAGRI",
    "banana": "MINAGRI",
    "cassava": "MINAGRI",
    "beans": "MINAGRI",
    "rice": "MINAGRI",
    "sweet potatoes": "MINAGRI",
    "extension services": "MINAGRI",
    "poultry": "MINAGRI",
    "animal feeds": "MINAGRI",
    "milk": "MINAGRI",
    "food production": "MINAGRI",
    "fisheries": "MINAGRI",
    "bee keeping": "MINAGRI",
    "rural farming": "MINAGRI",
    "mechanization": "MINAGRI",
    "cooperatives": "MINAGRI",
    "farm input": "MINAGRI",
    "green farming": "MINAGRI",
    "value chain": "MINAGRI",
    "farming subsidies": "MINAGRI",
    "agricultural finance": "MINAGRI",
    "farm tools": "MINAGRI",
    "water catchment": "MINAGRI",
    "terracing": "MINAGRI",
    "climate smart": "MINAGRI",
    "irrigation scheme": "MINAGRI",
    "nursery bed": "MINAGRI",
    "food storage": "MINAGRI",

    // MINEDUC

    "schools": "MINEDUC",
    "teachers": "MINEDUC",
    "students": "MINEDUC",
    "classroom": "MINEDUC",
    "tvet": "MINEDUC",
    "education": "MINEDUC",
    "learning": "MINEDUC",
    "e-learning": "MINEDUC",
    "curriculum": "MINEDUC",
    "textbooks": "MINEDUC",
    "literacy": "MINEDUC",
    "numeracy": "MINEDUC",
    "nursery": "MINEDUC",
    "primary": "MINEDUC",
    "secondary": "MINEDUC",
    "university": "MINEDUC",
    "tertiary": "MINEDUC",
    "higher education": "MINEDUC",
    "board exams": "MINEDUC",
    "teachers' salary": "MINEDUC",
    "school feeding": "MINEDUC",
    "class size": "MINEDUC",
    "dropout": "MINEDUC",
    "inclusive education": "MINEDUC",
    "private school": "MINEDUC",
    "public school": "MINEDUC",
    "bursary": "MINEDUC",
    "scholarship": "MINEDUC",
    "lesson plans": "MINEDUC",
    "national exams": "MINEDUC",
    "teacher training": "MINEDUC",
    "school infrastructure": "MINEDUC",
    "special needs": "MINEDUC",
    "education policy": "MINEDUC",
    "ICT in schools": "MINEDUC",
    "smart classroom": "MINEDUC",
    "school transport": "MINEDUC",
    "technical school": "MINEDUC",
    "REPU": "MINEDUC",
    "REBA": "MINEDUC",
    "school registration": "MINEDUC",
    "teaching aids": "MINEDUC",
    "MOOCs": "MINEDUC",
    "Kinyarwanda class": "MINEDUC",
    "academic calendar": "MINEDUC",
    "school equipment": "MINEDUC",
    "TVET center": "MINEDUC",

    // MINAFET
    "diplomacy": "MINAFET",
    "embassies": "MINAFET",
    "passport": "MINAFET",
    "visa": "MINAFET",
    "consular services": "MINAFET",
    "international cooperation": "MINAFET",
    "foreign affairs": "MINAFET",
    "bilateral relations": "MINAFET",
    "ambassador": "MINAFET",
    "diplomatic mission": "MINAFET",
    "foreign policy": "MINAFET",
    "UN mission": "MINAFET",
    "consulate": "MINAFET",
    "Rwandan embassy": "MINAFET",
    "diplomatic passport": "MINAFET",
    "non-resident ambassador": "MINAFET",
    "foreign nationals": "MINAFET",
    "international treaties": "MINAFET",
    "international agreements": "MINAFET",
    "foreign ministry": "MINAFET",
    "diaspora": "MINAFET",
    "diplomatic corps": "MINAFET",
    "country accreditation": "MINAFET",
    "UNGA": "MINAFET",
    "diplomatic note": "MINAFET",
    "expatriate": "MINAFET",
    "visa application": "MINAFET",
    "travel advisory": "MINAFET",
    "passport renewal": "MINAFET",
    "global affairs": "MINAFET",
    "UNDP": "MINAFET",
    "UNESCO": "MINAFET",
    "peacekeeping": "MINAFET",
    "consular support": "MINAFET",
    "embassy appointment": "MINAFET",
    "e-passport": "MINAFET",
    "foreign investment": "MINAFET",
    "summit": "MINAFET",
    "foreign mission": "MINAFET",
    "state visit": "MINAFET",
    "Rwandans abroad": "MINAFET",
    "international conference": "MINAFET",
    "scholarship abroad": "MINAFET",
    "visa rejection": "MINAFET",
    "cross-border relations": "MINAFET",

    // MINADEF
    "military": "MINADEF",
    "army": "MINADEF",
    "border": "MINADEF",
    "defense": "MINADEF",
    "security": "MINADEF",
    "insecurity": "MINADEF",
    "terrorism": "MINADEF",
    "RDF": "MINADEF",
    "soldiers": "MINADEF",
    "troops": "MINADEF",
    "barracks": "MINADEF",
    "military training": "MINADEF",
    "gun": "MINADEF",
    "shooting": "MINADEF",
    "war": "MINADEF",
    "combat": "MINADEF",
    "recruitment": "MINADEF",
    "peace mission": "MINADEF",
    "military equipment": "MINADEF",
    "air force": "MINADEF",
    "navy": "MINADEF",
    "defense policy": "MINADEF",
    "special forces": "MINADEF",
    "paramilitary": "MINADEF",
    "defense budget": "MINADEF",
    "military intelligence": "MINADEF",
    "counter-terrorism": "MINADEF",
    "national security": "MINADEF",
    "weapons": "MINADEF",
    "hostile group": "MINADEF",
    "landmine": "MINADEF",
    "riot": "MINADEF",
    "conflict zone": "MINADEF",
    "homeland defense": "MINADEF",
    "defense cooperation": "MINADEF",
    "military base": "MINADEF",
    "army uniform": "MINADEF",
    "strategic defense": "MINADEF",
    "shootout": "MINADEF",
    "armed group": "MINADEF",
    "peacekeeping force": "MINADEF",
    "border patrol": "MINADEF",
    "command center": "MINADEF",
    "national guard": "MINADEF",
    "military hospital": "MINADEF"
  };

  final text = complaintText.toLowerCase();

  for (var entry in categoryRules.entries) {
    if (text.contains(entry.key.toLowerCase())) {
      return entry.value;
    }
  }

  return "General Complaints Office";
}
